### ISSUE TITLE
[zigpy-integration] - wiser thermostat with deCONZ do not behave correctly

### ISSUE THREAD

**Issue by zigbeefordomoticz** [sasu-drooz/Domoticz-Zigate#1090] opened 2022-03-11 16:14 UTC
Wiser thermostat required EndPoint Coordinator at Ep 0x0b

How to register additional Cooridnator Ep with deconz ?

When Wiser Thermostat is paired we get some messages like that
```

2022-03-11 16:11:15,467 DEBUG   :Frame received: 0x1cdf000c00050002bfaaffca
2022-03-11 16:11:16,600 DEBUG   :Frame received: 0x1ce0000c00050002bfaaffcf
2022-03-11 16:11:17,606 DEBUG   :Frame received: 0x1ce1000c00050002bfaaffd6
2022-03-11 16:11:18,611 DEBUG   :Frame received: 0x1ce2000c00050002bfaaffd5
2022-03-11 16:11:19,616 DEBUG   :Frame received: 0x1ce3000c00050002bfaaffd5
2022-03-11 16:11:21,663 DEBUG   :Frame received: 0x1ce4000c00050002bfaaffd6
2022-03-11 16:11:22,668 DEBUG   :Frame received: 0x1ce5000c00050002bfaaffd6
2022-03-11 16:11:23,675 DEBUG   :Frame received: 0x1ce6000c00050002bfaaffd6
2022-03-11 16:11:24,679 DEBUG   :Frame received: 0x1ce7000c00050002bfaaffd6
```

**Comment by pipiche38** [comment] 2022-03-13 09:47
@puddy Is there a possibility to register Additional Ep with zigpy-deconz ?

**Comment by Hedda** [comment] 2022-03-23 12:16
For reference, which exact model of Schneider Electric Wiser thermostat is it? 

@manup Have you tested any Schneider Electric Wiser ( legacy) devices like Wiser thermostats with ConBee 2 / RaspBee 2?

https://phoscon.de/en/conbee2/compatible

https://phoscon.de/en/support#compatibility-of-devices

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices

https://zigbee.blakadder.com/deconz.html

Only one TVR ("iTRV") model is listed as confirmed working with deCONZ/Phoscon in Blakadder's Zigbee compatibility repository:

https://zigbee.blakadder.com/Schneider_Electric_CCTFR6100.html

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4148

While several other models are not yet listed as confirmed working:

https://zigbee.blakadder.com/Schneider_Electric_EER53000.html

https://zigbee.blakadder.com/Schneider_Electric_EER51000.html

https://zigbee.blakadder.com/Schneider_Electric_CCTFR6400.html

**Comment by pipiche38** [comment] 2022-03-23 12:47
@hedda, the all Wiser Legacy and new works with our plugin with Zigate, ZZH/SonOff and all CCxxxx as well as the Silicon Labs eelabs coordinator.
For that we need to be able to add Endpoint to the Coordinator. For now there is no such feature available on zigpy-deconz. The limitation is not deconz itself it is the zigpy layer except if deconz is not able to add EndPoint (which is not my understanding).
So we need to extend the zigpy_deconz in order to address that feature as well as the possibility to update the Manufacturer Id which is used to respond to Node Descriptor request.

**Comment by puddly** [comment] 2022-03-23 14:52
> except if deconz is not able to add EndPoint (which is not my understanding).

I'm seeing no references to adding endpoints in the [deCONZ Serial Protocol spec](https://deconz.dresden-elektronik.de/raspbian/deCONZ-Serial-Protocol-en_1.21.pdf).  Are you sure you need to be able to add endpoints?  The Silicon Labs coordinator, for example, did not need to have this done, since it is capable of sending/receiving on any endpoint.

**Comment by pipiche38** [comment] 2022-03-23 16:31
@manup was responding to the question, https://github.com/dresden-elektronik/deconz-serial-protocol/issues/17#issuecomment-1066715693

**Comment by SylvainPer** [comment] 2022-03-28 11:23
Just manage to pair wiser devices on the conbee ii.
~~The end points are well managed without particular need like bellows.~~

<img width="1391" alt="Capture d’écran 2022-03-28 à 13 19 17" src="https://user-images.githubusercontent.com/48243214/160387755-e4a7ea36-c92a-4efe-b07b-318b6732ad07.png">

One thing weird, I didn't succeed to pair through a router, only directly to the key.

**Comment by SylvainPer** [comment] 2022-04-02 20:26
After some clarification with @pipiche38, my test wasn't relevant. The Bind Request is an outgoing request and it's well managed by the coordinator. The problem is when the device asked from and to an endpoint different from 01, in my case ep 0x11 to 0x11.
I've made some test on the different libraries with a wiser thermostat, the Report Attributes and Read Attributes requests are not transferred to the application level. The coordinator answer an ACK and nothing more:
<img width="1031" alt="ep11" src="https://user-images.githubusercontent.com/48243214/161399996-8d2c6bdc-1641-4f48-8009-f8486d1364bb.png">

@puddly as for the znp library, the register endpoint function is needed for those particular devices.

**Comment by pipiche38** [comment] 2022-04-29 15:27
Link to #1145 which is handling this issue. Closing that one

**Closed as completed by pipiche38** 2022-04-29 15:27 UTC
Labels: zigpy, Zigpy-Prio1, Zigpy-external, zigpy-deconz
